### ISSUE TITLE
m_privdeaf.so: segfaults on inspircd 2.0

### ISSUE THREAD

**Issue by voidzero** [inspircd/inspircd-extras#110]
Hello,

I just compiled inspircd 2.0 (3469711d) with gcc 7.1.0-r1 (Gentoo, amd64). It segfaults on m_privdeaf.so. I don't know why.

It was the first server of our network that I've updated. The other servers are running inspircd 2.0 (a923a030, 2016-12-29) compiled with gcc 4.9.3, there this problem does not occur.

Mark

**Comment by genius3000** [comment]
Was this a clean install with a fresh clone of the repo or system updates/upgrades and a quick re-compile? If the latter, try running `make distclean` (make sure the build directory is removed) and then re-run `./configure`, `make`, `make install`. If it's the former, debug logs of it trying to load (in a pastebin, gist, etc) would be helpful.

**Comment by SaberUK** [comment]
In addition to what @genius3000 asked for can you also start with `./inspircd debug` and when it crashes pastebin the output of `bt full`.

**Comment by voidzero** [comment]
Alright, I can probably do it this weekend. I'll keep you posted.

**Comment by SaberUK** [comment]
@voidzero Any updates?

**Comment by voidzero** [comment]
Ok, finally got around to it, I'm sorry for the delay!

```
Thu Oct 26 23:15:34 2017: ConfigReader is deprecated in 2.0; use ServerInstance->Config->ConfValue("key") or ->ConfTags("key") instead

Program received signal SIGSEGV, Segmentation fault.
ConfigTag::readString () at /var/home/ircd/src/inspircd.git/src/configparser.cpp:405
405             for(std::vector<KeyVal>::iterator j = items.begin(); j != items.end(); ++j)
```

Can this be a config error? I only loaded the module, no extra configuration.

**Comment by Adam-** [comment]
Looks like this is the ```if(this)``` UB again from ReadFlag(). If you add a empty <privdeaf> configuration block in your config it will fix it.

**Comment by SaberUK** [comment]
I have also just updated these modules to not use the deprecated config reading system which doesn't have this issue.
