### ISSUE TITLE
Support DCC over OTR

### ISSUE THREAD

**Issue by SoniEx2** [inspircd/inspircd-extras#112]
Any cryptanalysts know how to break OTR?

**Comment by SISheogorath** [comment]
DCC, as the name already suggests, is a direct Client to Client connection. InspIRCd is not involved. So we can't implement anything like this.

And since this is a bug tracker and not a security mailing list we don't provide crypto analysis. So you should search for a different audience.

Thanks~

**Comment by SaberUK** [comment]
This is a client feature not a server feature. Please ask the author of your client to implement this instead.

**Comment by SoniEx2** [comment]
This is a bug with the dccblock module. It doesn't support DCC over OTR.

**Comment by SoniEx2** [comment]
Please reopen?
