### ISSUE TITLE
m_override_umode umodexpire setting cannot be changed from the default 10m

### ISSUE THREAD

**Issue by KoraggKnightWolf** [inspircd/inspircd-extras#125]
When utilizing m_override_umode with m_override and adding the configuration options to the override tag in the config, the changing of the option umodeexpiry to e.g. 30m from 10m does not change when it expires. This always occurs after 10 minutes. Other settings as setting snoonunset from yes to no got applied perfectly after just /REHASH. Yet umodeexpiry did not change even after /REHASH and even /GRELOADMODULE and then a /REHASH.

This behaviour is confirmed to occur on InspIRCd 2.0.25

**Comment by genius3000** [comment]
Can you paste your `<override ...>` tag here (in code formatting) please. I'm testing and currently awaiting the expiry of a 'ActiveOper' (set for 30m). Other than that, debug snotices show things are set correctly during a REHASH.
I suspect you have the config variable typed incorrectly as you have it typed here two different ways (umod**e**xpire and umod**ee**xpir**y**) and it's actually umod**ee**xpir**e**

**Comment by KoraggKnightWolf** [comment]
Dear genius3000,

Thank you for the test, I hope you can find out what is causing this odd bug and thank you for pointing out the mistake in the spelling of the name, here is the override tag in my modules.conf 

<override noisy="yes" requirekey="yes"
umodexpire="30m" snoonset="yes" snoonunset="yes" snoonexpire="no">

**Comment by KoraggKnightWolf** [comment]
<override noisy="yes" requirekey="yes"
umodexpire="30m" snoonset="yes" snoonunset="yes" snoonexpire="no">

**Comment by KoraggKnightWolf** [comment]
apparently it removes the code format thus I will include a pastebin sample that is going to be available for 1 week: https://pastebin.com/xHzV4B3z

**Comment by GLolol** [comment]
It looks like you wrote "umodexpire" instead of "umode**e**xpire". There should be two e's in the key name.

**Comment by KoraggKnightWolf** [comment]
just why did the config not complain about an unknown parameter/key?

**Comment by KoraggKnightWolf** [comment]
upon testing the settings are now applied as desired, no longer do they unset after the default of 10m. I will therefor close this issue and thank you two very much for your time and effort and apologize for any inconveniences this simple mistake of a typo might have caused.

Best regards,

Koragg

**Comment by genius3000** [comment]
@KoraggKnightWolf the config doesn't complain about it being unknown because it doesn't **know** it's unknown. It has no way to know if another module wants that value or not. Copy&Paste from the module is always the safest solution.
Also, there is a bug here yet. The `ActiveOper` object isn't properly destroyed when unsetting the mode, which is why I seen old ones expire when they shouldn't exist anymore.

**Comment by KoraggKnightWolf** [comment]
Thank you for explaining it I just assumed it would know that the value is not known and as there is a bug after all I will reopen this issue until it is fixed and yes I noticed that when I unset the mode myself, it will still expire, I forgot about that in the hurry of the previous error

**Comment by SaberUK** [comment]
This should be fixed now. Please reopen if that is not the case.
