### ISSUE TITLE
[MISLEADING] Why is there still a 2.1 folder as well as a reference [to a 2.1 mod] in modules.lst?

### ISSUE THREAD

**Issue by DonMusto** [inspircd/inspircd-extras#15]
Since 2.1 was deemed deprecated and the only module in the 2.1 folder has a duplicate in 2.0, the 2.1 folder should be deleted and the reference to the 2.1 invisible module, which is at the very end of modules.lst, should be excised.

~DM

**Comment by SaberUK** [comment]
Is there any point in doing this? It's not hurting anyone by just existing.
