### ISSUE TITLE
Add $account variable to m_conn_vhost fetching the (NickServ) accountname

### ISSUE THREAD

**Issue by KoraggKnightWolf** [inspircd/inspircd-extras#172]
Dear InspIRCd Developers,

Extending m_conn_vhost with a $account variable to fetch the (NickServ) accountname of entities could be used to give them unique (cloaked) hosts when e.g. implementing a restricted TOR solution (combining this in a connect class with requireaccount="on" for restricting TOR to SASL auth users similar to freenode). This would make it more feasible to utilize an own TOR exit node for users while still being able to restrict it (further with m_conn_accounts though that is beyond the scope of this feature request). 
Any other restricted connection access point, e.g. commonly used and large VPNs (for example Private Internet Access et al) could also be restricted this way, giving users unique hosts by which to ban them from channels. (As this cannot change their real host it will not make network bans "easier" this way).

I hope these reasons are sensible enough to justify an extension of this module.

Thank You very much for Your time and effort in advance.

Regards,

Koragg

**Comment by SISheogorath** [comment]
First of all there is already:

https://github.com/inspircd/inspircd-extras/blob/master/2.0/m_accounthost.cpp that basically does exactly what you describe here.

Also I would recommend to have a look at extban `R:<accountname>` which provides all ban functionality you request already in https://github.com/inspircd/inspircd/blob/insp20/src/modules/m_services_account.cpp

Finally vhosts for accounts unique or not should may be handled by the services package. Atheme and I'm quite sure anope as well allow to assign users a vhost on register which means they'll get it everytime they log in.

So even when it's a nice idea to extend the module, I don't see an urgent need for it.

**Comment by genius3000** [comment]
Since this addition has merit and causes no harm to the original behavior (if wanted) of setting a vHost per connect block, I've gone ahead and PR'ed an update.
