### ISSUE TITLE
m_conn_require randomly disconnects for criteria not checked

### ISSUE THREAD

**Issue by KoraggKnightWolf** [inspircd/inspircd-extras#182]
It appears that m_conn_require randomly disconnects people for missing components when for example requirecap="off" and also at times for version when also requireversion="off" for all connect classes and it defaults to off too, what could be the cause of this? 

I will attempt to get backlogs of users but not sure if this will be successful and it happens several times a day when the various require options are even set extra off just to be safe.

Regards,

Koragg

**Comment by KoraggKnightWolf** [comment]
Slight edit: I meant to say they are set to "no" not "off" though it appears that getBool would work with either of those and I used the one mentioned in the modules's documentation.

**Comment by genius3000** [comment]
Have you verified the module is **actually** blocking them? If you unload the module, do they connect fine, without having changed anything on their end?

**Comment by KoraggKnightWolf** [comment]
There are no bans in effect or such that would keep them out (as they can connect from the same address blocked) and it is always the snomask generated by conn_require, though I will temporarily unload it for like a day and then report my findings back.

**Comment by Cronus89** [comment]
It can be other reasons. Such as their clients not accepting the ssl cert. This module isn't 100% sure it's the reason. So it's log message is a best guess.

**Comment by KoraggKnightWolf** [comment]
Thanks for the hints and I think it might have been that because this module increases the connect holding time during registration that increasing timeout seems to have helped. I raised it from default 10 to 15 and it seems so far to be ok, I'll observe snotices for a few more days and see if anymore false positives occur.

Regards,

Koragg

**Comment by KoraggKnightWolf** [comment]
Still receiving issues from the module, I will keep it unloaded for several days, to the end of the week should be good, to see if there are any reasons users get blocked that "do not make sense" (e.g. blocked without being network banned, not using invalid nicks etc). Hopefully this will eliminate the causes, but that would mean it is most likely the module. I do not htink it is the cert's as the same users sometimes connect and then get blocekd again, completely randomly. from the same connection and client.

**Comment by genius3000** [comment]
Have you gotten any client logs of what is actually happening?

**Comment by KoraggKnightWolf** [comment]
Unfortunately not as of right now, the people it occurs to are not on the most tech savvy side though I will try when it happens to them again/they are online again.
