### ISSUE TITLE
[BUG]: m_invisible -> 2.0

### ISSUE THREAD

**Issue by westor7** [inspircd/inspircd-extras#19]
Hello,

I have check that when i join into an channel and using +Q ok working, but when i do from my clone the channel /hop the nick's that has +Q does not hiding from me.
- Thanks!

**Comment by DarkTexas** [comment]
> It's a third party module, which translates to "unsupported" and "anything can happen".

According to that it wont get fixed? That /whois issue is the only Issue that's blocking us from using it for hiding our Bots in the Channels. >_<

Anyone who *could* fix it?

https://raw.github.com/ShutterQuick/inspircd-extras/ef2ebe49bac561f8fb6ebf38f7d6bef39f398921/2.0/m_invisible.cpp

**Comment by SaberUK** [comment]
There is no real reason to want to hide a bot other to spy on people and that is is unethical at best and illegal at worst. We will not support it or fix any bugs in this module.
