### ISSUE TITLE
Request m_randomnotice

### ISSUE THREAD

**Issue by UselessOper** [inspircd/inspircd-extras#42]
I would like to request a module that sends local users a random notice every X minutes. For example `<randomnotice delay="5" file="data/randomnotice.db">` so every 5 minutes the local users would receive a notice from the server with a random line from `randomnotice.db`.

**Comment by bigfoot547** [comment]
@UselessOper: Couldn't you make a bot do this? It could send `STATS l` then notice all users on the list. Or better yet, make it oper on connect to an oper with `users/mass-message` then just send `NOTICE $* :text` every so often. Bots are so easy to write nowadays. If you can't make one, in my spare time, I guess I could make one.
