### ISSUE TITLE
Add m_flashpolicyd to Windows binary

### ISSUE THREAD

**Issue by ChrisLangsenkamp** [inspircd/inspircd-extras#59]
Please, so I can deal with flash webchat client without a deparate daemon? Using light IRC because it's heavily customizable to suit our needs.

Thanks!

**Comment by attilamolnar** [comment]
Hello! Unfortunately we don't have the time required to ship third party modules from inspircd-extras as part of the Windows installer as it requires a non-trivial amount of (mainly testing) work. We have to draw a line somewhere and the two repos clearly define where this line is.
m_flashpolicyd was added to the next major version, though. For 2.0, you can download Visual Studio Express (available from Microsoft at no cost) and compile the third party modules yourself by following the instructions in win/README.txt.

If someone from the community wants to provide compiled third party modules for Windows, I'm happy to mention their site and contact information.
