### ISSUE TITLE
m_sqlite3.so undefined symbol

### ISSUE THREAD

**Issue by shibumi** [inspircd/inspircd-extras#62]
Hello,
I am not sure but I think there is something wrong with compiling m_sqlite3.cpp..
the compile-process completed but I got the following error while starting inspircd:

```
[*] Unable to load m_sqlite3.so: /home/irc/build/modules/m_sqlite3.so: undefined symbol: sqlite3_column_text
```

**Comment by md-5** [comment]
Is libsqlite3-0 installed? (Assuming Debian/Ubuntu based)

**Comment by shibumi** [comment]
yes libsqlite3-0 is installed.. I get the following message while the building process:

```
Checking version of package sqlite3 is >= 3.3... Yes (version 3.7.13)
Locating include directory for package sqlite3 for module m_sqlite3.cpp... -I/usr/include  -DVERSION_SQLITE3="0.0" (cached)
```

**Comment by SaberUK** [comment]
If you are using a Debian-derived distribution you will need to ensure you have all of the packages for sqlite installed as well as pkg-config. Make sure you haven't got a different library version to that of the headers.

If that is all okay can you pastebin the output of the following commands:

```
ldd ./run/modules/m_sqlite3.so
grep sqlite3 ./.config.cache
```

**Comment by shibumi** [comment]
@SaberUK 
Thank you very much.  seems like it was a 0.0 in the cache
deleting .config.cache solved the problem
