### ISSUE TITLE
m_xmlsocket

### ISSUE THREAD

**Issue by ghost** [inspircd/inspircd-extras#79]
Hi,

Our network has ~1,200 users who connect using a Flash client that we had custom made years ago.

We are on a very old InspIRCd version and really we need to update to the latest version to take advantage of some newer features that we need but at the moment not having `m_xmlsocket` is preventing us from updating.

Switching to another client is not an option as our users like the existing client. Is there a developer who can please update `m_xmlsocket` for us?

Thanks a lot,
Alex

**Comment by Sheogorath-SI** [comment]
Why not simply improve the flash client itself? `m_xmlsocket` was a "diry hack" to fix some issues of flash. Besides the fact that flash itself is "a bug"/"broken by design", fixing the client is the better way to go. Especially because InspIRCd 2.2 is coming (some day) and there exactly the same problem remains.

In other words: Fixing the client itself will fix the issue in a "nearly forever" way instead of fixing the issue by porting a unneeded module every server version.

**Comment by alex-jch** [comment]
@Sheogorath-SI We don't have the source code.

**Comment by Sheogorath-SI** [comment]
So in your statement:
> Our network has ~1,200 users who connect using a Flash client that we had custom made years ago.

"we" means "they"?

**Comment by alex-jch** [comment]
@Sheogorath-SI Huh? We paid a developer to create it. We don't own the source code. Anyway such comments are not relevant to why I opened this. There is a reason that we need the module and that reason still stands. I could argue that other modules in here are pointless but that's opinion.

**Comment by attilamolnar** [comment]
@alex-jch https://gist.github.com/attilamolnar/60a56d1aa0c1c513f731

I haven't had the chance to test it much, feedback is welcome.

**Comment by alex-jch** [comment]
@attilamolnar Thanks. I'll test.

**Comment by SaberUK** [comment]
@ghost Did this module work for you? If so then i'll commit it.

**Comment by SISheogorath** [comment]
Can we keep this module out here? It leads to dead ends. Like the shitty flash client IrCQnet used back then. And I know no other client that ever needed it.

I would like to not support people who think flash clients are the future :x

**Comment by SaberUK** [comment]
Nobody has to support it. The entire point of -extras is weird niche stuff that very few people will want.

Flash will be dead in 2020 regardless.
