### ISSUE TITLE
Port m_override_umode to 2.2

### ISSUE THREAD

**Issue by bonnedav** [inspircd/inspircd-extras#84]
Could someone please port m_override_umode to inspircd 2. 2? I tryed but i could not figure out what I_OnRehash turned into.

**Comment by SaberUK** [comment]
2.1 is long dead. You should not be using it.

**Comment by bonnedav** [comment]
Then what version is the master branch?

**Comment by SaberUK** [comment]
The master branch is 2.2, but you really shouldn't be using that in production. Porting modules to it at this point is pretty pointless considering how the API is not stable yet.

**Comment by bonnedav** [comment]
I am not using it in production. I am just playing around with it.

**Comment by bonnedav** [comment]
Could you please tell me what replaced I_OnRehash.

**Comment by SaberUK** [comment]
Nothing. OnRehash was replaced with ReadConfig. You also shouldn't hook to events now as it is done automatically.

**Comment by attilamolnar** [comment]
This feature will be shipping in the next major InspIRCd version.

**Comment by bonnedav** [comment]
Ok. Thank you.
