### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by BhanuproS** [inspircd/inspircd-extras#98]
ircd@Bhanu:~/inspircd-2.0.23$ make
*************************************
*       BUILDING INSPIRCD           *
*                                   *
*   This will take a *long* time.   *
*     Why not read our wiki at      *
*     http://wiki.inspircd.org      *
*  while you wait for make to run?  *
*************************************
        BUILD:              bancache.cpp
        BUILD:              base.cpp
        BUILD:              channels.cpp
        BUILD:              cidr.cpp
        BUILD:              command_parse.cpp
        BUILD:              commands.cpp
        BUILD:              configparser.cpp
        BUILD:              configreader.cpp
        BUILD:              cull_list.cpp
        BUILD:              dns.cpp
        BUILD:              dynamic.cpp
        BUILD:              filelogger.cpp
        BUILD:              hashcomp.cpp
        BUILD:              helperfuncs.cpp
{standard input}: Assembler messages:
{standard input}:1633: Warning: end of file not at end of a line; newline inserted
{standard input}:3668: Error: junk `@' after expression
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
An error occured when executing: g++ -o obj/helperfuncs.o -pipe -fPIC -DPIC -pedantic -Woverloaded-virtual -Wshadow -Wformat=2 -Wmissing-format-attribute -Wall -O2 -g1 -Iinclude -c /home/ircd/inspircd-2.0.23/src/helperfuncs.cpp
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
real.mk:40: recipe for target 'obj/helperfuncs.o' failed
make[1]: *** [obj/helperfuncs.o] Error 4
GNUmakefile:164: recipe for target 'target' failed
make: *** [target] Error 2
ircd@Bhanu:~/inspircd-2.0.23$

**Comment by SaberUK** [comment]
>g++: internal compiler error: Killed (program cc1plus)

This is a bug with your compiler rather than InspIRCd.

**Comment by attilamolnar** [comment]
This is an issue on the system you are trying to compile InspIRCd on, not an issue the code of InspIRCd.
